version: '3'
services:
  myblog-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: myblog-mysql
    image: myblog-mysql
    ports:
      - 3306:3306
    networks:
      - spring_cloud_default

  myblog-redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
    restart: always
    container_name: myblog-redis
    hostname: myblog-redis
    networks:
      - spring_cloud_default

  myblog-register:
    build:
      context: ./myblog-register
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
    container_name: myblog-register
    hostname: myblog-register
    image: myblog-register
    networks:
      - spring_cloud_default

  myblog-gateway:
    build:
      context: ./myblog-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: myblog-gateway
    hostname: myblog-gateway
    image: myblog-gateway
    networks:
      - spring_cloud_default

  myblog-auth:
    build:
      context: ./myblog-auth
    restart: always
    container_name: myblog-auth
    hostname: myblog-auth
    image: myblog-auth
    networks:
      - spring_cloud_default

  myblog-upms:
    build:
      context: ./myblog-upms/myblog-upms-biz
    restart: always
    container_name: myblog-upms
    hostname: myblog-upms
    image: myblog-upms
    networks:
      - spring_cloud_default

  myblog-monitor:
    build:
      context: ./myblog-visual/myblog-monitor
    restart: always
    ports:
      - 5001:5001
    container_name: myblog-monitor
    hostname: myblog-monitor
    image: myblog-monitor
    networks:
      - spring_cloud_default

  myblog-codegen:
    build:
      context: ./myblog-visual/myblog-codegen
    restart: always
    container_name: myblog-codegen
    hostname: myblog-codegen
    image: myblog-codegen
    networks:
      - spring_cloud_default

  myblog-quartz:
    build:
      context: ./myblog-visual/myblog-quartz
    restart: always
    image: myblog-quartz
    container_name: myblog-quartz
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge
